name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build packages
      run: npm run build
    
    - name: Configure npm
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}
    
    - name: Publish packages
      run: |
        npm publish --workspace @dependency-cycle-analyzer/web --access public
        npm publish --workspace @dependency-cycle-analyzer/plugin --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          packages/web/dist/**
          packages/plugin/dist/** 